export const UNSCHEDULED_LEVEL_ID = 'UNSCHEDULED_LEVEL_ID';
export const UNSCHEDULED_TECHNOLOGY_ID = 'UNSCHEDULED_TECHNOLOGY_ID';
export const UNSCHEDULED_RESEARCH_AREA_ID = 'UNSCHEDULED_RESEARCH_AREA_ID';
